services:
  backend:
    build: ./backend
    container_name: vnrcampusnavigator2_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      DB_NAME: campus_navigation
    depends_on:
      - mongodb
    networks:
      - campus-network

  frontend:
    build: ./frontend
    container_name: vnrcampusnavigator2_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - campus-network

  mongodb:
    image: mongo:7
    container_name: vnrcampusnavigator2_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - campus-network

volumes:
  mongodb_data:

networks:
  campus-network:
    driver: bridge